---
# defaults to be overridden in jobs.include
os: linux
dist: xenial
language: minimal

stages:
  - compile
  - test

jobs:
  exclude:
    - dist: xenial

  include:
    - stage: compile
    - &stage
      name: Compile
      os: linux
      dist: focal
      jdk: openjdk17
      install: >-
        pushd /tmp
        && wget 'https://ftp.gnu.org/gnu/make/make-4.4.1.tar.gz'
        && tar xzf make-4.4.1.tar.gz
        && cd make-4.4.1
        && ./configure --prefix=/usr/local
        && sudo make install
        && popd
      script: >-
        make compile

    - <<: *stage
      name: Test
      script: >-
        make test
