---
version: 2.1

executors:
  docker:
    docker:
      - image: bdockerimg/bmakelib:0.8.0--opensuse-tumbleweed
        environment:
          LANG: en_US.UTF-8
          JVM_OPTS: -Xmx1024m
    working_directory: ~/bjforth
    resource_class: medium

jobs:

  test:
    executor: docker
    steps:
      - run:
          name: Install the runtime
          command: >-
            zypper --non-interactive refresh
            && zypper --non-interactive install java-21-openjdk-devel
            && { source /etc/profile || true; }
            && cpan install Term::ANSIColor

      - checkout

      - restore_cache:
          keys:
            - dependencies-{{ checksum "bjforth/build.gradle" }}
            - dependencies-

      - run:
          name: Fetch the dependencies and compile
          command: >-
            make compile

      - save_cache:
          paths:
            - ~/.gradle
          key: dependencies-{{ checksum "bjforth/build.gradle" }}

      - run:
          name: Run the tests
          command: >-
            make test
            
      - run:
          name: Run the E2E tests
          command: >-
            make VERSION=vpr-pipeline e2e-test

      - store_artifacts:
          path: bjforth/build/reports
          destination: test-reports

      - store_test_results:
          path: bjforth/build/test-results

      - persist_to_workspace:
          root: bjforth/build
          paths:
            - reports

  test_coverage:
    executor: docker
    steps:
      - run:
          name: Install Python
          command: >-
            zypper --non-interactive refresh
            && zypper --non-interactive install python311

      - checkout

      - run:
          name: Install Codecov-cli
          command: >-
            python3 -m venv .env
            && source .env/bin/activate
            && pip install -r requirements.txt

      - attach_workspace:
          at: bjforth/build

      - run:
          name: Upload the coverage reports
          command: >-
            source .env/bin/activate
            && codecovcli --verbose \
               upload-process \
               --token "${CODECOV_TOKEN}" \
               --git-service github \
               --fail-on-error \
               --dir=bjforth/build/reports/jacoco/test \
               --report-type=coverage

  license_scan:
    executor: docker
    steps:
      - run:
          name: Install Fossa-cli
          command: >-
            wget -O - \
               --header='Cache-Control: no-cache' \
               'https://raw.githubusercontent.com/fossas/fossa-cli/master/install-latest.sh' \
            | bash

      - checkout
      - run:
          name: Analyse licenses
          command: fossa analyze
          working_directory: ~/bjforth

  release:
    executor: docker

    steps:
      - run:
          name: Install the development tools
          command: >-
            zypper --non-interactive refresh
            && zypper --non-interactive install go java-21-openjdk-devel
            && { source /etc/profile || true; }
            && GOPATH=/usr/local go install github.com/tcnksm/ghr@latest

      - checkout

      - run:
          name: Run E2E tests
          command: >-
            make VERSION=${CIRCLE_TAG} e2e-test

      - run:
          name: Build the packages
          command: >-
            make VERSION=${CIRCLE_TAG} package

      - run:
          name: Create the GitHub release
          command: >-
            ghr \
              -t ${GITHUB_TOKEN} \
              -u ${GITHUB_USERNAME} \
              -r ${CIRCLE_PROJECT_REPONAME} \
              -c ${CIRCLE_SHA1} \
              -n ${CIRCLE_TAG} \
              -draft \
              -soft \
              -generatenotes \
              ${CIRCLE_TAG} \
              bjforth/build/libs

workflows:
  build_test:
    jobs:
      - license_scan
      - test
      - test_coverage:
          requires:
            - test
  release:
    jobs:
      - release:
          filters:
            tags:
              only: /^v.+/
            branches:
              ignore: /.*/
