---

version: 2

jobs:
  build:
    docker:
      - image: opensuse/tumbleweed:latest
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx1024m

    steps:
      - run:
          name: Install the runtime
          command: >-
            zypper --non-interactive refresh
            && zypper --non-interactive install java-17-openjdk-devel make
            && { source /etc/profile || true; }

      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "bjforth/build.gradle" }}
            - v1-dependencies-

      - run:
          name: Fetch the dependencies and compile
          command: >-
            make compile

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "bjforth/build.gradle" }}

      - run:
          name: Run the tests
          command: >-
            make test
